### ISSUE TITLE
分时图 长按十字线问题

### ISSUE THREAD

**Issue by YangSugar** [DongZai/KChartDemo#1]
分时图中 长按，当滑动到稍低点 十字线点不会滑到下边
<img width="314" alt="2016-09-14 2 54 43" src="https://cloud.githubusercontent.com/assets/16461564/18502836/2612e2a0-7a8c-11e6-8315-20ae5918ec4d.png">

**Comment by DerClown** [comment]
分时图中的长按手势调用方法（longPressedEvent），你可以自行修改！@YangSugar [
<img width="837" alt="52c0af10-5f71-4d61-b4d0-746a3b2cf7e3" src="https://cloud.githubusercontent.com/assets/10142573/18607590/9380d738-7d03-11e6-9876-8e37fae9c7a8.png">
](url)

**Comment by YangSugar** [comment]
好的 感谢感谢。

**Comment by YangSugar** [comment]
分时图：
有时候数据会崩溃 报错的是 数组越界。 

这个时候我修改 pointPadding 这个属性， 就不会崩溃。  有数据时候 有时候崩溃， 有时候不会。
起初pointPadding = 1.6  我改成2时候就不崩溃。  
是因为里边算X轴算宽度 跟这个 pointPadding 关系吗？

<img width="330" alt="2016-09-19 11 24 25" src="https://cloud.githubusercontent.com/assets/16461564/18621892/cdc9d0bc-7e5b-11e6-80b5-0053ab34bba1.png">
<img width="588" alt="2016-09-19 11 24 10" src="https://cloud.githubusercontent.com/assets/16461564/18621894/cf91c0e4-7e5b-11e6-8072-504b0e4fc24d.png">

**Comment by blmyself** [comment]
@YangSugar 数组越界的情况我也遇到了，请问你解决了么?  还有那个十字线跟随你修改好了么，能给参考下么

**Comment by DerClown** [comment]
最新代码已经修复好，最新代码是不会出现数组越界问题，这个是计算时间轴出了问题。和pointPadding无关。 @YangSugar   @blmyself 更新最新的代码。

**Comment by YangSugar** [comment]
@blmyself  十字线修改把那句话注掉就行了

**Comment by blmyself** [comment]
好的，谢谢~ @YangSugar @DerClown

**Comment by blmyself** [comment]
![code](https://cloud.githubusercontent.com/assets/914295/18657238/ce8db6ec-7f2a-11e6-9564-76178b174aab.png)
这里当lineRawData.count<_kCount的时候，你数据截取会有问题，range会超过lineRawData的范围

**Comment by DerClown** [comment]
@blmyself  当lineRawData.count<_kCount，直接取lineRawData.count的个数就ok。
