### ISSUE TITLE
很好用，可是有几个问题

### ISSUE THREAD

**Issue by Arvind-qrj** [DongZai/KChartDemo#10]
我想用第三方的，仅仅为了画k线，但是看了下demo，发现里面并不是纯粹的画线，传入数据格式，通讯方式，感觉是有点不方便，因为业务原因只能用自己的通讯方式，从demo里还要剥离通讯层，最后我都不知道哪部分是我需要的，那些是我用不到的。
希望能改成纯粹的画线的第三方，最好有一个传入数据的方法或属性，给个说明，从pod安装。感觉这样会好一些。

**Comment by DerClown** [comment]
感谢你给出的宝贵意见！
