### ISSUE TITLE
关于数组越界 为什么设置pointPadding数值为1.5时候，会崩溃？

### ISSUE THREAD

**Issue by YangSugar** [DongZai/KChartDemo#2]
我下的就是最新版本。我想看着您写的项目写一遍，希望您不忙时候帮忙能解答下， 不胜感激！！
这里有点不明白 ceil(quarteredWidth/_pointPadding) 为什么要这么算？ 

self.kGraphDrawCount = floor(((self.frame.size.width - self.leftMargin - self.rightMargin -self.pointPadding) / self.pointPadding));

<img width="1056" alt="2016-09-22 2 08 03" src="https://cloud.githubusercontent.com/assets/16461564/18738410/00f28244-80ce-11e6-9581-23fdb437c2b0.png">

**Comment by DerClown** [comment]
@YangSugar 感谢你的提议！此处问题已经修复！是我想的过于复杂！更新最新代码。看最新标注

**Comment by YangSugar** [comment]
@DerClown  好的！👌👌👌！
