### ISSUE TITLE
请问怎么控制x轴分时图 宽度？ 除了设置pointpading

### ISSUE THREAD

**Issue by YangSugar** [DongZai/KChartDemo#3]
比如图中，后台返回的数据只能到15：00左右，还要预先留出到凌晨6：00的空间。 这个分时图显示宽度除了用pointpading控制么？  我能想到的就是补全下数据， 把剩下补充到凌晨6点。 您有什么好的思路实现图中样式呢？  希望能给些思路哈
![img_2647](https://cloud.githubusercontent.com/assets/16461564/18904982/78036e42-8593-11e6-9d46-b3ceb40fd86a.PNG)

**Comment by YangSugar** [comment]
你好，我提的问题我自己解决的方法就是， 实际数据之后添加0数据,然后截取有数据部分绘制。
宽度如图片1那么算的， 不知道您有什么好的思路呢？   

还有源代码中，见图2, 因为大部分需求都是这种需要留出空白，补全数据，会加入0情况， 图2的方法会带导致绘图不正确。 并且之前已经有最大值最小值传入， 没必要再算一遍吧？

<img width="585" alt="2016-09-30 1 59 48" src="https://cloud.githubusercontent.com/assets/16461564/18982299/9e9c03f4-8717-11e6-99dc-ed8ee1c1b45f.png">
<img width="592" alt="2016-09-30 2 02 50" src="https://cloud.githubusercontent.com/assets/16461564/18982300/a009b740-8717-11e6-8d62-473a6458a4bd.png">

**Comment by DerClown** [comment]
不全数据是最好的办法。这个数据就看你自己怎么取

**Comment by DerClown** [comment]
如果是空白的，我建议补充一个数据，然后就回绘制一条直线，这样子处理应该是最好的。数据有了再重新刷一次。

**Comment by greezi** [comment]
@YangSugar 我目前也遇到了跟你一样的需求,请问你是怎么做的呢?能否分享一下具体实现思路.谢谢
